site_name: Firefly Field Day Logger
site_url: https://packetwarriors.com/firefly-logger
site_description: Documentation for the Firefly Field Day Logger
site_author: Jason McCormick N8EI
plugins:
  - search
  - glightbox
  - print-site
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
copyright: This work © 2024-2025 by Jason McCormick N8EI is licensed under CC BY-NC-SA 4.0.
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  logo: img/firefly.svg
  favicon: img/favicon.ico
  palette:
    scheme: allstarlink
extra_css:
  - stylesheets/extra.css
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
nav:
  - Home: index.md
  - "Setup & Admin" :
    - "Security Notes":  security.md
    - "Appliance Installation" : appliance.md
    - "Software Installation": installation.md
    - "Configuration": configs.md
    - "Helper Scripts" : helpers.md
    - "WSJT to FFDL" : wsjt2ffdl.md
  - "User Guide": 
    - "Basics" : basic.md
    - "Screens" : screens.md
    - "Setup WSJT-X" : wsjtx.md